// Code generated by internal/rtl/cmd/genarabic — DO NOT EDIT.
//
// Sources (Unicode 17.0.0):
//   UnicodeData.txt    sha256:2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c
//   ArabicShaping.txt  sha256:39afa01e680e27d0fd10b67a9b27be13fbaa3d0efecfb5be45991de9a0d267d0
//   https://unicode.org/Public/17.0.0/ucd/UnicodeData.txt
//   https://unicode.org/Public/17.0.0/ucd/ArabicShaping.txt
//
// Regenerate: go run ./internal/rtl/cmd/genarabic
//
// Design constraints (see provenance.md §Arabic shaping gate for PR 2):
//   - Only Prose clusters are shaped; Code/Path/URL are never modified.
//   - Presentation Forms are written to Cluster.Text only; they never
//     enter the journal, search indexes, or RestoreFromSource output.
//   - Letters that are Joining_Type D but lack initial/medial glyphs in
//     Presentation Forms-B are recorded in missingForms and treated according
//     to the Logical Preservation Contract (missing forms remain the logical rune).

package rtl

// joiningClass is the Unicode Joining_Type property (ArabicShaping.txt).
type joiningClass uint8

const (
	joiningClassNon     joiningClass = iota // U: non-joining
	joiningClassDual                        // D: dual-joining
	joiningClassRight                       // R: right-joining
	joiningClassLeft                        // L: left-joining
	joiningClassCausing                     // C: join-causing (Tatweel, ZWJ)
	joiningClassTrans                       // T: transparent (diacritics)
)

// String returns the single-letter Unicode identifier for the Joining_Type.
func (c joiningClass) String() string {
	switch c {
	case joiningClassDual:
		return "D"
	case joiningClassRight:
		return "R"
	case joiningClassLeft:
		return "L"
	case joiningClassCausing:
		return "C"
	case joiningClassTrans:
		return "T"
	default:
		return "U"
	}
}

// joiningType returns the Joining_Type for a rune.
// Source: ArabicShaping-17.0.0.txt and UnicodeData-17.0.0.txt (Mn/Me default T).
func joiningType(r rune) joiningClass {
	switch r {
	case 0x0600:
		return joiningClassNon
	case 0x0601:
		return joiningClassNon
	case 0x0602:
		return joiningClassNon
	case 0x0603:
		return joiningClassNon
	case 0x0604:
		return joiningClassNon
	case 0x0605:
		return joiningClassNon
	case 0x0608:
		return joiningClassNon
	case 0x060B:
		return joiningClassNon
	case 0x0610:
		return joiningClassTrans
	case 0x0611:
		return joiningClassTrans
	case 0x0612:
		return joiningClassTrans
	case 0x0613:
		return joiningClassTrans
	case 0x0614:
		return joiningClassTrans
	case 0x0615:
		return joiningClassTrans
	case 0x0616:
		return joiningClassTrans
	case 0x0617:
		return joiningClassTrans
	case 0x0618:
		return joiningClassTrans
	case 0x0619:
		return joiningClassTrans
	case 0x061A:
		return joiningClassTrans
	case 0x0620:
		return joiningClassDual
	case 0x0621:
		return joiningClassNon
	case 0x0622:
		return joiningClassRight
	case 0x0623:
		return joiningClassRight
	case 0x0624:
		return joiningClassRight
	case 0x0625:
		return joiningClassRight
	case 0x0626:
		return joiningClassDual
	case 0x0627:
		return joiningClassRight
	case 0x0628:
		return joiningClassDual
	case 0x0629:
		return joiningClassRight
	case 0x062A:
		return joiningClassDual
	case 0x062B:
		return joiningClassDual
	case 0x062C:
		return joiningClassDual
	case 0x062D:
		return joiningClassDual
	case 0x062E:
		return joiningClassDual
	case 0x062F:
		return joiningClassRight
	case 0x0630:
		return joiningClassRight
	case 0x0631:
		return joiningClassRight
	case 0x0632:
		return joiningClassRight
	case 0x0633:
		return joiningClassDual
	case 0x0634:
		return joiningClassDual
	case 0x0635:
		return joiningClassDual
	case 0x0636:
		return joiningClassDual
	case 0x0637:
		return joiningClassDual
	case 0x0638:
		return joiningClassDual
	case 0x0639:
		return joiningClassDual
	case 0x063A:
		return joiningClassDual
	case 0x063B:
		return joiningClassDual
	case 0x063C:
		return joiningClassDual
	case 0x063D:
		return joiningClassDual
	case 0x063E:
		return joiningClassDual
	case 0x063F:
		return joiningClassDual
	case 0x0640:
		return joiningClassCausing
	case 0x0641:
		return joiningClassDual
	case 0x0642:
		return joiningClassDual
	case 0x0643:
		return joiningClassDual
	case 0x0644:
		return joiningClassDual
	case 0x0645:
		return joiningClassDual
	case 0x0646:
		return joiningClassDual
	case 0x0647:
		return joiningClassDual
	case 0x0648:
		return joiningClassRight
	case 0x0649:
		return joiningClassDual
	case 0x064A:
		return joiningClassDual
	case 0x064B:
		return joiningClassTrans
	case 0x064C:
		return joiningClassTrans
	case 0x064D:
		return joiningClassTrans
	case 0x064E:
		return joiningClassTrans
	case 0x064F:
		return joiningClassTrans
	case 0x0650:
		return joiningClassTrans
	case 0x0651:
		return joiningClassTrans
	case 0x0652:
		return joiningClassTrans
	case 0x0653:
		return joiningClassTrans
	case 0x0654:
		return joiningClassTrans
	case 0x0655:
		return joiningClassTrans
	case 0x0656:
		return joiningClassTrans
	case 0x0657:
		return joiningClassTrans
	case 0x0658:
		return joiningClassTrans
	case 0x0659:
		return joiningClassTrans
	case 0x065A:
		return joiningClassTrans
	case 0x065B:
		return joiningClassTrans
	case 0x065C:
		return joiningClassTrans
	case 0x065D:
		return joiningClassTrans
	case 0x065E:
		return joiningClassTrans
	case 0x065F:
		return joiningClassTrans
	case 0x066E:
		return joiningClassDual
	case 0x066F:
		return joiningClassDual
	case 0x0670:
		return joiningClassTrans
	case 0x0671:
		return joiningClassRight
	case 0x0672:
		return joiningClassRight
	case 0x0673:
		return joiningClassRight
	case 0x0674:
		return joiningClassNon
	case 0x0675:
		return joiningClassRight
	case 0x0676:
		return joiningClassRight
	case 0x0677:
		return joiningClassRight
	case 0x0678:
		return joiningClassDual
	case 0x0679:
		return joiningClassDual
	case 0x067A:
		return joiningClassDual
	case 0x067B:
		return joiningClassDual
	case 0x067C:
		return joiningClassDual
	case 0x067D:
		return joiningClassDual
	case 0x067E:
		return joiningClassDual
	case 0x067F:
		return joiningClassDual
	case 0x0680:
		return joiningClassDual
	case 0x0681:
		return joiningClassDual
	case 0x0682:
		return joiningClassDual
	case 0x0683:
		return joiningClassDual
	case 0x0684:
		return joiningClassDual
	case 0x0685:
		return joiningClassDual
	case 0x0686:
		return joiningClassDual
	case 0x0687:
		return joiningClassDual
	case 0x0688:
		return joiningClassRight
	case 0x0689:
		return joiningClassRight
	case 0x068A:
		return joiningClassRight
	case 0x068B:
		return joiningClassRight
	case 0x068C:
		return joiningClassRight
	case 0x068D:
		return joiningClassRight
	case 0x068E:
		return joiningClassRight
	case 0x068F:
		return joiningClassRight
	case 0x0690:
		return joiningClassRight
	case 0x0691:
		return joiningClassRight
	case 0x0692:
		return joiningClassRight
	case 0x0693:
		return joiningClassRight
	case 0x0694:
		return joiningClassRight
	case 0x0695:
		return joiningClassRight
	case 0x0696:
		return joiningClassRight
	case 0x0697:
		return joiningClassRight
	case 0x0698:
		return joiningClassRight
	case 0x0699:
		return joiningClassRight
	case 0x069A:
		return joiningClassDual
	case 0x069B:
		return joiningClassDual
	case 0x069C:
		return joiningClassDual
	case 0x069D:
		return joiningClassDual
	case 0x069E:
		return joiningClassDual
	case 0x069F:
		return joiningClassDual
	case 0x06A0:
		return joiningClassDual
	case 0x06A1:
		return joiningClassDual
	case 0x06A2:
		return joiningClassDual
	case 0x06A3:
		return joiningClassDual
	case 0x06A4:
		return joiningClassDual
	case 0x06A5:
		return joiningClassDual
	case 0x06A6:
		return joiningClassDual
	case 0x06A7:
		return joiningClassDual
	case 0x06A8:
		return joiningClassDual
	case 0x06A9:
		return joiningClassDual
	case 0x06AA:
		return joiningClassDual
	case 0x06AB:
		return joiningClassDual
	case 0x06AC:
		return joiningClassDual
	case 0x06AD:
		return joiningClassDual
	case 0x06AE:
		return joiningClassDual
	case 0x06AF:
		return joiningClassDual
	case 0x06B0:
		return joiningClassDual
	case 0x06B1:
		return joiningClassDual
	case 0x06B2:
		return joiningClassDual
	case 0x06B3:
		return joiningClassDual
	case 0x06B4:
		return joiningClassDual
	case 0x06B5:
		return joiningClassDual
	case 0x06B6:
		return joiningClassDual
	case 0x06B7:
		return joiningClassDual
	case 0x06B8:
		return joiningClassDual
	case 0x06B9:
		return joiningClassDual
	case 0x06BA:
		return joiningClassDual
	case 0x06BB:
		return joiningClassDual
	case 0x06BC:
		return joiningClassDual
	case 0x06BD:
		return joiningClassDual
	case 0x06BE:
		return joiningClassDual
	case 0x06BF:
		return joiningClassDual
	case 0x06C0:
		return joiningClassRight
	case 0x06C1:
		return joiningClassDual
	case 0x06C2:
		return joiningClassDual
	case 0x06C3:
		return joiningClassRight
	case 0x06C4:
		return joiningClassRight
	case 0x06C5:
		return joiningClassRight
	case 0x06C6:
		return joiningClassRight
	case 0x06C7:
		return joiningClassRight
	case 0x06C8:
		return joiningClassRight
	case 0x06C9:
		return joiningClassRight
	case 0x06CA:
		return joiningClassRight
	case 0x06CB:
		return joiningClassRight
	case 0x06CC:
		return joiningClassDual
	case 0x06CD:
		return joiningClassRight
	case 0x06CE:
		return joiningClassDual
	case 0x06CF:
		return joiningClassRight
	case 0x06D0:
		return joiningClassDual
	case 0x06D1:
		return joiningClassDual
	case 0x06D2:
		return joiningClassRight
	case 0x06D3:
		return joiningClassRight
	case 0x06D5:
		return joiningClassRight
	case 0x06D6:
		return joiningClassTrans
	case 0x06D7:
		return joiningClassTrans
	case 0x06D8:
		return joiningClassTrans
	case 0x06D9:
		return joiningClassTrans
	case 0x06DA:
		return joiningClassTrans
	case 0x06DB:
		return joiningClassTrans
	case 0x06DC:
		return joiningClassTrans
	case 0x06DD:
		return joiningClassNon
	case 0x06DF:
		return joiningClassTrans
	case 0x06E0:
		return joiningClassTrans
	case 0x06E1:
		return joiningClassTrans
	case 0x06E2:
		return joiningClassTrans
	case 0x06E3:
		return joiningClassTrans
	case 0x06E4:
		return joiningClassTrans
	case 0x06E7:
		return joiningClassTrans
	case 0x06E8:
		return joiningClassTrans
	case 0x06EA:
		return joiningClassTrans
	case 0x06EB:
		return joiningClassTrans
	case 0x06EC:
		return joiningClassTrans
	case 0x06ED:
		return joiningClassTrans
	case 0x06EE:
		return joiningClassRight
	case 0x06EF:
		return joiningClassRight
	case 0x06FA:
		return joiningClassDual
	case 0x06FB:
		return joiningClassDual
	case 0x06FC:
		return joiningClassDual
	case 0x06FF:
		return joiningClassDual
	case 0x070F:
		return joiningClassTrans
	case 0x0710:
		return joiningClassRight
	case 0x0712:
		return joiningClassDual
	case 0x0713:
		return joiningClassDual
	case 0x0714:
		return joiningClassDual
	case 0x0715:
		return joiningClassRight
	case 0x0716:
		return joiningClassRight
	case 0x0717:
		return joiningClassRight
	case 0x0718:
		return joiningClassRight
	case 0x0719:
		return joiningClassRight
	case 0x071A:
		return joiningClassDual
	case 0x071B:
		return joiningClassDual
	case 0x071C:
		return joiningClassDual
	case 0x071D:
		return joiningClassDual
	case 0x071E:
		return joiningClassRight
	case 0x071F:
		return joiningClassDual
	case 0x0720:
		return joiningClassDual
	case 0x0721:
		return joiningClassDual
	case 0x0722:
		return joiningClassDual
	case 0x0723:
		return joiningClassDual
	case 0x0724:
		return joiningClassDual
	case 0x0725:
		return joiningClassDual
	case 0x0726:
		return joiningClassDual
	case 0x0727:
		return joiningClassDual
	case 0x0728:
		return joiningClassRight
	case 0x0729:
		return joiningClassDual
	case 0x072A:
		return joiningClassRight
	case 0x072B:
		return joiningClassDual
	case 0x072C:
		return joiningClassRight
	case 0x072D:
		return joiningClassDual
	case 0x072E:
		return joiningClassDual
	case 0x072F:
		return joiningClassRight
	case 0x074D:
		return joiningClassRight
	case 0x074E:
		return joiningClassDual
	case 0x074F:
		return joiningClassDual
	case 0x0750:
		return joiningClassDual
	case 0x0751:
		return joiningClassDual
	case 0x0752:
		return joiningClassDual
	case 0x0753:
		return joiningClassDual
	case 0x0754:
		return joiningClassDual
	case 0x0755:
		return joiningClassDual
	case 0x0756:
		return joiningClassDual
	case 0x0757:
		return joiningClassDual
	case 0x0758:
		return joiningClassDual
	case 0x0759:
		return joiningClassRight
	case 0x075A:
		return joiningClassRight
	case 0x075B:
		return joiningClassRight
	case 0x075C:
		return joiningClassDual
	case 0x075D:
		return joiningClassDual
	case 0x075E:
		return joiningClassDual
	case 0x075F:
		return joiningClassDual
	case 0x0760:
		return joiningClassDual
	case 0x0761:
		return joiningClassDual
	case 0x0762:
		return joiningClassDual
	case 0x0763:
		return joiningClassDual
	case 0x0764:
		return joiningClassDual
	case 0x0765:
		return joiningClassDual
	case 0x0766:
		return joiningClassDual
	case 0x0767:
		return joiningClassDual
	case 0x0768:
		return joiningClassDual
	case 0x0769:
		return joiningClassDual
	case 0x076A:
		return joiningClassDual
	case 0x076B:
		return joiningClassRight
	case 0x076C:
		return joiningClassRight
	case 0x076D:
		return joiningClassDual
	case 0x076E:
		return joiningClassDual
	case 0x076F:
		return joiningClassDual
	case 0x0770:
		return joiningClassDual
	case 0x0771:
		return joiningClassRight
	case 0x0772:
		return joiningClassDual
	case 0x0773:
		return joiningClassRight
	case 0x0774:
		return joiningClassRight
	case 0x0775:
		return joiningClassDual
	case 0x0776:
		return joiningClassDual
	case 0x0777:
		return joiningClassDual
	case 0x0778:
		return joiningClassRight
	case 0x0779:
		return joiningClassRight
	case 0x077A:
		return joiningClassDual
	case 0x077B:
		return joiningClassDual
	case 0x077C:
		return joiningClassDual
	case 0x077D:
		return joiningClassDual
	case 0x077E:
		return joiningClassDual
	case 0x077F:
		return joiningClassDual
	case 0x07CA:
		return joiningClassDual
	case 0x07CB:
		return joiningClassDual
	case 0x07CC:
		return joiningClassDual
	case 0x07CD:
		return joiningClassDual
	case 0x07CE:
		return joiningClassDual
	case 0x07CF:
		return joiningClassDual
	case 0x07D0:
		return joiningClassDual
	case 0x07D1:
		return joiningClassDual
	case 0x07D2:
		return joiningClassDual
	case 0x07D3:
		return joiningClassDual
	case 0x07D4:
		return joiningClassDual
	case 0x07D5:
		return joiningClassDual
	case 0x07D6:
		return joiningClassDual
	case 0x07D7:
		return joiningClassDual
	case 0x07D8:
		return joiningClassDual
	case 0x07D9:
		return joiningClassDual
	case 0x07DA:
		return joiningClassDual
	case 0x07DB:
		return joiningClassDual
	case 0x07DC:
		return joiningClassDual
	case 0x07DD:
		return joiningClassDual
	case 0x07DE:
		return joiningClassDual
	case 0x07DF:
		return joiningClassDual
	case 0x07E0:
		return joiningClassDual
	case 0x07E1:
		return joiningClassDual
	case 0x07E2:
		return joiningClassDual
	case 0x07E3:
		return joiningClassDual
	case 0x07E4:
		return joiningClassDual
	case 0x07E5:
		return joiningClassDual
	case 0x07E6:
		return joiningClassDual
	case 0x07E7:
		return joiningClassDual
	case 0x07E8:
		return joiningClassDual
	case 0x07E9:
		return joiningClassDual
	case 0x07EA:
		return joiningClassDual
	case 0x07FA:
		return joiningClassCausing
	case 0x0840:
		return joiningClassRight
	case 0x0841:
		return joiningClassDual
	case 0x0842:
		return joiningClassDual
	case 0x0843:
		return joiningClassDual
	case 0x0844:
		return joiningClassDual
	case 0x0845:
		return joiningClassDual
	case 0x0846:
		return joiningClassRight
	case 0x0847:
		return joiningClassRight
	case 0x0848:
		return joiningClassDual
	case 0x0849:
		return joiningClassRight
	case 0x084A:
		return joiningClassDual
	case 0x084B:
		return joiningClassDual
	case 0x084C:
		return joiningClassDual
	case 0x084D:
		return joiningClassDual
	case 0x084E:
		return joiningClassDual
	case 0x084F:
		return joiningClassDual
	case 0x0850:
		return joiningClassDual
	case 0x0851:
		return joiningClassDual
	case 0x0852:
		return joiningClassDual
	case 0x0853:
		return joiningClassDual
	case 0x0854:
		return joiningClassRight
	case 0x0855:
		return joiningClassDual
	case 0x0856:
		return joiningClassRight
	case 0x0857:
		return joiningClassRight
	case 0x0858:
		return joiningClassRight
	case 0x0860:
		return joiningClassDual
	case 0x0861:
		return joiningClassNon
	case 0x0862:
		return joiningClassDual
	case 0x0863:
		return joiningClassDual
	case 0x0864:
		return joiningClassDual
	case 0x0865:
		return joiningClassDual
	case 0x0866:
		return joiningClassNon
	case 0x0867:
		return joiningClassRight
	case 0x0868:
		return joiningClassDual
	case 0x0869:
		return joiningClassRight
	case 0x086A:
		return joiningClassRight
	case 0x0870:
		return joiningClassRight
	case 0x0871:
		return joiningClassRight
	case 0x0872:
		return joiningClassRight
	case 0x0873:
		return joiningClassRight
	case 0x0874:
		return joiningClassRight
	case 0x0875:
		return joiningClassRight
	case 0x0876:
		return joiningClassRight
	case 0x0877:
		return joiningClassRight
	case 0x0878:
		return joiningClassRight
	case 0x0879:
		return joiningClassRight
	case 0x087A:
		return joiningClassRight
	case 0x087B:
		return joiningClassRight
	case 0x087C:
		return joiningClassRight
	case 0x087D:
		return joiningClassRight
	case 0x087E:
		return joiningClassRight
	case 0x087F:
		return joiningClassRight
	case 0x0880:
		return joiningClassRight
	case 0x0881:
		return joiningClassRight
	case 0x0882:
		return joiningClassRight
	case 0x0883:
		return joiningClassCausing
	case 0x0884:
		return joiningClassCausing
	case 0x0885:
		return joiningClassCausing
	case 0x0886:
		return joiningClassDual
	case 0x0887:
		return joiningClassNon
	case 0x0888:
		return joiningClassNon
	case 0x0889:
		return joiningClassDual
	case 0x088A:
		return joiningClassDual
	case 0x088B:
		return joiningClassDual
	case 0x088C:
		return joiningClassDual
	case 0x088D:
		return joiningClassDual
	case 0x088E:
		return joiningClassRight
	case 0x088F:
		return joiningClassDual
	case 0x0890:
		return joiningClassNon
	case 0x0891:
		return joiningClassNon
	case 0x08A0:
		return joiningClassDual
	case 0x08A1:
		return joiningClassDual
	case 0x08A2:
		return joiningClassDual
	case 0x08A3:
		return joiningClassDual
	case 0x08A4:
		return joiningClassDual
	case 0x08A5:
		return joiningClassDual
	case 0x08A6:
		return joiningClassDual
	case 0x08A7:
		return joiningClassDual
	case 0x08A8:
		return joiningClassDual
	case 0x08A9:
		return joiningClassDual
	case 0x08AA:
		return joiningClassRight
	case 0x08AB:
		return joiningClassRight
	case 0x08AC:
		return joiningClassRight
	case 0x08AD:
		return joiningClassNon
	case 0x08AE:
		return joiningClassRight
	case 0x08AF:
		return joiningClassDual
	case 0x08B0:
		return joiningClassDual
	case 0x08B1:
		return joiningClassRight
	case 0x08B2:
		return joiningClassRight
	case 0x08B3:
		return joiningClassDual
	case 0x08B4:
		return joiningClassDual
	case 0x08B5:
		return joiningClassDual
	case 0x08B6:
		return joiningClassDual
	case 0x08B7:
		return joiningClassDual
	case 0x08B8:
		return joiningClassDual
	case 0x08B9:
		return joiningClassRight
	case 0x08BA:
		return joiningClassDual
	case 0x08BB:
		return joiningClassDual
	case 0x08BC:
		return joiningClassDual
	case 0x08BD:
		return joiningClassDual
	case 0x08BE:
		return joiningClassDual
	case 0x08BF:
		return joiningClassDual
	case 0x08C0:
		return joiningClassDual
	case 0x08C1:
		return joiningClassDual
	case 0x08C2:
		return joiningClassDual
	case 0x08C3:
		return joiningClassDual
	case 0x08C4:
		return joiningClassDual
	case 0x08C5:
		return joiningClassDual
	case 0x08C6:
		return joiningClassDual
	case 0x08C7:
		return joiningClassDual
	case 0x08C8:
		return joiningClassDual
	case 0x08E2:
		return joiningClassNon
	case 0x1806:
		return joiningClassNon
	case 0x1807:
		return joiningClassDual
	case 0x180A:
		return joiningClassCausing
	case 0x180E:
		return joiningClassNon
	case 0x1820:
		return joiningClassDual
	case 0x1821:
		return joiningClassDual
	case 0x1822:
		return joiningClassDual
	case 0x1823:
		return joiningClassDual
	case 0x1824:
		return joiningClassDual
	case 0x1825:
		return joiningClassDual
	case 0x1826:
		return joiningClassDual
	case 0x1827:
		return joiningClassDual
	case 0x1828:
		return joiningClassDual
	case 0x1829:
		return joiningClassDual
	case 0x182A:
		return joiningClassDual
	case 0x182B:
		return joiningClassDual
	case 0x182C:
		return joiningClassDual
	case 0x182D:
		return joiningClassDual
	case 0x182E:
		return joiningClassDual
	case 0x182F:
		return joiningClassDual
	case 0x1830:
		return joiningClassDual
	case 0x1831:
		return joiningClassDual
	case 0x1832:
		return joiningClassDual
	case 0x1833:
		return joiningClassDual
	case 0x1834:
		return joiningClassDual
	case 0x1835:
		return joiningClassDual
	case 0x1836:
		return joiningClassDual
	case 0x1837:
		return joiningClassDual
	case 0x1838:
		return joiningClassDual
	case 0x1839:
		return joiningClassDual
	case 0x183A:
		return joiningClassDual
	case 0x183B:
		return joiningClassDual
	case 0x183C:
		return joiningClassDual
	case 0x183D:
		return joiningClassDual
	case 0x183E:
		return joiningClassDual
	case 0x183F:
		return joiningClassDual
	case 0x1840:
		return joiningClassDual
	case 0x1841:
		return joiningClassDual
	case 0x1842:
		return joiningClassDual
	case 0x1843:
		return joiningClassDual
	case 0x1844:
		return joiningClassDual
	case 0x1845:
		return joiningClassDual
	case 0x1846:
		return joiningClassDual
	case 0x1847:
		return joiningClassDual
	case 0x1848:
		return joiningClassDual
	case 0x1849:
		return joiningClassDual
	case 0x184A:
		return joiningClassDual
	case 0x184B:
		return joiningClassDual
	case 0x184C:
		return joiningClassDual
	case 0x184D:
		return joiningClassDual
	case 0x184E:
		return joiningClassDual
	case 0x184F:
		return joiningClassDual
	case 0x1850:
		return joiningClassDual
	case 0x1851:
		return joiningClassDual
	case 0x1852:
		return joiningClassDual
	case 0x1853:
		return joiningClassDual
	case 0x1854:
		return joiningClassDual
	case 0x1855:
		return joiningClassDual
	case 0x1856:
		return joiningClassDual
	case 0x1857:
		return joiningClassDual
	case 0x1858:
		return joiningClassDual
	case 0x1859:
		return joiningClassDual
	case 0x185A:
		return joiningClassDual
	case 0x185B:
		return joiningClassDual
	case 0x185C:
		return joiningClassDual
	case 0x185D:
		return joiningClassDual
	case 0x185E:
		return joiningClassDual
	case 0x185F:
		return joiningClassDual
	case 0x1860:
		return joiningClassDual
	case 0x1861:
		return joiningClassDual
	case 0x1862:
		return joiningClassDual
	case 0x1863:
		return joiningClassDual
	case 0x1864:
		return joiningClassDual
	case 0x1865:
		return joiningClassDual
	case 0x1866:
		return joiningClassDual
	case 0x1867:
		return joiningClassDual
	case 0x1868:
		return joiningClassDual
	case 0x1869:
		return joiningClassDual
	case 0x186A:
		return joiningClassDual
	case 0x186B:
		return joiningClassDual
	case 0x186C:
		return joiningClassDual
	case 0x186D:
		return joiningClassDual
	case 0x186E:
		return joiningClassDual
	case 0x186F:
		return joiningClassDual
	case 0x1870:
		return joiningClassDual
	case 0x1871:
		return joiningClassDual
	case 0x1872:
		return joiningClassDual
	case 0x1873:
		return joiningClassDual
	case 0x1874:
		return joiningClassDual
	case 0x1875:
		return joiningClassDual
	case 0x1876:
		return joiningClassDual
	case 0x1877:
		return joiningClassDual
	case 0x1878:
		return joiningClassDual
	case 0x1880:
		return joiningClassNon
	case 0x1881:
		return joiningClassNon
	case 0x1882:
		return joiningClassNon
	case 0x1883:
		return joiningClassNon
	case 0x1884:
		return joiningClassNon
	case 0x1885:
		return joiningClassTrans
	case 0x1886:
		return joiningClassTrans
	case 0x1887:
		return joiningClassDual
	case 0x1888:
		return joiningClassDual
	case 0x1889:
		return joiningClassDual
	case 0x188A:
		return joiningClassDual
	case 0x188B:
		return joiningClassDual
	case 0x188C:
		return joiningClassDual
	case 0x188D:
		return joiningClassDual
	case 0x188E:
		return joiningClassDual
	case 0x188F:
		return joiningClassDual
	case 0x1890:
		return joiningClassDual
	case 0x1891:
		return joiningClassDual
	case 0x1892:
		return joiningClassDual
	case 0x1893:
		return joiningClassDual
	case 0x1894:
		return joiningClassDual
	case 0x1895:
		return joiningClassDual
	case 0x1896:
		return joiningClassDual
	case 0x1897:
		return joiningClassDual
	case 0x1898:
		return joiningClassDual
	case 0x1899:
		return joiningClassDual
	case 0x189A:
		return joiningClassDual
	case 0x189B:
		return joiningClassDual
	case 0x189C:
		return joiningClassDual
	case 0x189D:
		return joiningClassDual
	case 0x189E:
		return joiningClassDual
	case 0x189F:
		return joiningClassDual
	case 0x18A0:
		return joiningClassDual
	case 0x18A1:
		return joiningClassDual
	case 0x18A2:
		return joiningClassDual
	case 0x18A3:
		return joiningClassDual
	case 0x18A4:
		return joiningClassDual
	case 0x18A5:
		return joiningClassDual
	case 0x18A6:
		return joiningClassDual
	case 0x18A7:
		return joiningClassDual
	case 0x18A8:
		return joiningClassDual
	case 0x18AA:
		return joiningClassDual
	case 0x200C:
		return joiningClassNon
	case 0x200D:
		return joiningClassCausing
	case 0x202F:
		return joiningClassNon
	case 0x2066:
		return joiningClassNon
	case 0x2067:
		return joiningClassNon
	case 0x2068:
		return joiningClassNon
	case 0x2069:
		return joiningClassNon
	case 0xA840:
		return joiningClassDual
	case 0xA841:
		return joiningClassDual
	case 0xA842:
		return joiningClassDual
	case 0xA843:
		return joiningClassDual
	case 0xA844:
		return joiningClassDual
	case 0xA845:
		return joiningClassDual
	case 0xA846:
		return joiningClassDual
	case 0xA847:
		return joiningClassDual
	case 0xA848:
		return joiningClassDual
	case 0xA849:
		return joiningClassDual
	case 0xA84A:
		return joiningClassDual
	case 0xA84B:
		return joiningClassDual
	case 0xA84C:
		return joiningClassDual
	case 0xA84D:
		return joiningClassDual
	case 0xA84E:
		return joiningClassDual
	case 0xA84F:
		return joiningClassDual
	case 0xA850:
		return joiningClassDual
	case 0xA851:
		return joiningClassDual
	case 0xA852:
		return joiningClassDual
	case 0xA853:
		return joiningClassDual
	case 0xA854:
		return joiningClassDual
	case 0xA855:
		return joiningClassDual
	case 0xA856:
		return joiningClassDual
	case 0xA857:
		return joiningClassDual
	case 0xA858:
		return joiningClassDual
	case 0xA859:
		return joiningClassDual
	case 0xA85A:
		return joiningClassDual
	case 0xA85B:
		return joiningClassDual
	case 0xA85C:
		return joiningClassDual
	case 0xA85D:
		return joiningClassDual
	case 0xA85E:
		return joiningClassDual
	case 0xA85F:
		return joiningClassDual
	case 0xA860:
		return joiningClassDual
	case 0xA861:
		return joiningClassDual
	case 0xA862:
		return joiningClassDual
	case 0xA863:
		return joiningClassDual
	case 0xA864:
		return joiningClassDual
	case 0xA865:
		return joiningClassDual
	case 0xA866:
		return joiningClassDual
	case 0xA867:
		return joiningClassDual
	case 0xA868:
		return joiningClassDual
	case 0xA869:
		return joiningClassDual
	case 0xA86A:
		return joiningClassDual
	case 0xA86B:
		return joiningClassDual
	case 0xA86C:
		return joiningClassDual
	case 0xA86D:
		return joiningClassDual
	case 0xA86E:
		return joiningClassDual
	case 0xA86F:
		return joiningClassDual
	case 0xA870:
		return joiningClassDual
	case 0xA871:
		return joiningClassDual
	case 0xA872:
		return joiningClassLeft
	case 0xA873:
		return joiningClassNon
	case 0x10AC0:
		return joiningClassDual
	case 0x10AC1:
		return joiningClassDual
	case 0x10AC2:
		return joiningClassDual
	case 0x10AC3:
		return joiningClassDual
	case 0x10AC4:
		return joiningClassDual
	case 0x10AC5:
		return joiningClassRight
	case 0x10AC6:
		return joiningClassNon
	case 0x10AC7:
		return joiningClassRight
	case 0x10AC8:
		return joiningClassNon
	case 0x10AC9:
		return joiningClassRight
	case 0x10ACA:
		return joiningClassRight
	case 0x10ACB:
		return joiningClassNon
	case 0x10ACC:
		return joiningClassNon
	case 0x10ACD:
		return joiningClassLeft
	case 0x10ACE:
		return joiningClassRight
	case 0x10ACF:
		return joiningClassRight
	case 0x10AD0:
		return joiningClassRight
	case 0x10AD1:
		return joiningClassRight
	case 0x10AD2:
		return joiningClassRight
	case 0x10AD3:
		return joiningClassDual
	case 0x10AD4:
		return joiningClassDual
	case 0x10AD5:
		return joiningClassDual
	case 0x10AD6:
		return joiningClassDual
	case 0x10AD7:
		return joiningClassLeft
	case 0x10AD8:
		return joiningClassDual
	case 0x10AD9:
		return joiningClassDual
	case 0x10ADA:
		return joiningClassDual
	case 0x10ADB:
		return joiningClassDual
	case 0x10ADC:
		return joiningClassDual
	case 0x10ADD:
		return joiningClassRight
	case 0x10ADE:
		return joiningClassDual
	case 0x10ADF:
		return joiningClassDual
	case 0x10AE0:
		return joiningClassDual
	case 0x10AE1:
		return joiningClassRight
	case 0x10AE2:
		return joiningClassNon
	case 0x10AE3:
		return joiningClassNon
	case 0x10AE4:
		return joiningClassRight
	case 0x10AEB:
		return joiningClassDual
	case 0x10AEC:
		return joiningClassDual
	case 0x10AED:
		return joiningClassDual
	case 0x10AEE:
		return joiningClassDual
	case 0x10AEF:
		return joiningClassRight
	case 0x10B80:
		return joiningClassDual
	case 0x10B81:
		return joiningClassRight
	case 0x10B82:
		return joiningClassDual
	case 0x10B83:
		return joiningClassRight
	case 0x10B84:
		return joiningClassRight
	case 0x10B85:
		return joiningClassRight
	case 0x10B86:
		return joiningClassDual
	case 0x10B87:
		return joiningClassDual
	case 0x10B88:
		return joiningClassDual
	case 0x10B89:
		return joiningClassRight
	case 0x10B8A:
		return joiningClassDual
	case 0x10B8B:
		return joiningClassDual
	case 0x10B8C:
		return joiningClassRight
	case 0x10B8D:
		return joiningClassDual
	case 0x10B8E:
		return joiningClassRight
	case 0x10B8F:
		return joiningClassRight
	case 0x10B90:
		return joiningClassDual
	case 0x10B91:
		return joiningClassRight
	case 0x10BA9:
		return joiningClassRight
	case 0x10BAA:
		return joiningClassRight
	case 0x10BAB:
		return joiningClassRight
	case 0x10BAC:
		return joiningClassRight
	case 0x10BAD:
		return joiningClassDual
	case 0x10BAE:
		return joiningClassDual
	case 0x10BAF:
		return joiningClassNon
	case 0x10D00:
		return joiningClassLeft
	case 0x10D01:
		return joiningClassDual
	case 0x10D02:
		return joiningClassDual
	case 0x10D03:
		return joiningClassDual
	case 0x10D04:
		return joiningClassDual
	case 0x10D05:
		return joiningClassDual
	case 0x10D06:
		return joiningClassDual
	case 0x10D07:
		return joiningClassDual
	case 0x10D08:
		return joiningClassDual
	case 0x10D09:
		return joiningClassDual
	case 0x10D0A:
		return joiningClassDual
	case 0x10D0B:
		return joiningClassDual
	case 0x10D0C:
		return joiningClassDual
	case 0x10D0D:
		return joiningClassDual
	case 0x10D0E:
		return joiningClassDual
	case 0x10D0F:
		return joiningClassDual
	case 0x10D10:
		return joiningClassDual
	case 0x10D11:
		return joiningClassDual
	case 0x10D12:
		return joiningClassDual
	case 0x10D13:
		return joiningClassDual
	case 0x10D14:
		return joiningClassDual
	case 0x10D15:
		return joiningClassDual
	case 0x10D16:
		return joiningClassDual
	case 0x10D17:
		return joiningClassDual
	case 0x10D18:
		return joiningClassDual
	case 0x10D19:
		return joiningClassDual
	case 0x10D1A:
		return joiningClassDual
	case 0x10D1B:
		return joiningClassDual
	case 0x10D1C:
		return joiningClassDual
	case 0x10D1D:
		return joiningClassDual
	case 0x10D1E:
		return joiningClassDual
	case 0x10D1F:
		return joiningClassDual
	case 0x10D20:
		return joiningClassDual
	case 0x10D21:
		return joiningClassDual
	case 0x10D22:
		return joiningClassRight
	case 0x10D23:
		return joiningClassDual
	case 0x10EC2:
		return joiningClassRight
	case 0x10EC3:
		return joiningClassDual
	case 0x10EC4:
		return joiningClassDual
	case 0x10EC6:
		return joiningClassDual
	case 0x10EC7:
		return joiningClassDual
	case 0x10F30:
		return joiningClassDual
	case 0x10F31:
		return joiningClassDual
	case 0x10F32:
		return joiningClassDual
	case 0x10F33:
		return joiningClassRight
	case 0x10F34:
		return joiningClassDual
	case 0x10F35:
		return joiningClassDual
	case 0x10F36:
		return joiningClassDual
	case 0x10F37:
		return joiningClassDual
	case 0x10F38:
		return joiningClassDual
	case 0x10F39:
		return joiningClassDual
	case 0x10F3A:
		return joiningClassDual
	case 0x10F3B:
		return joiningClassDual
	case 0x10F3C:
		return joiningClassDual
	case 0x10F3D:
		return joiningClassDual
	case 0x10F3E:
		return joiningClassDual
	case 0x10F3F:
		return joiningClassDual
	case 0x10F40:
		return joiningClassDual
	case 0x10F41:
		return joiningClassDual
	case 0x10F42:
		return joiningClassDual
	case 0x10F43:
		return joiningClassDual
	case 0x10F44:
		return joiningClassDual
	case 0x10F45:
		return joiningClassNon
	case 0x10F51:
		return joiningClassDual
	case 0x10F52:
		return joiningClassDual
	case 0x10F53:
		return joiningClassDual
	case 0x10F54:
		return joiningClassRight
	case 0x10F70:
		return joiningClassDual
	case 0x10F71:
		return joiningClassDual
	case 0x10F72:
		return joiningClassDual
	case 0x10F73:
		return joiningClassDual
	case 0x10F74:
		return joiningClassRight
	case 0x10F75:
		return joiningClassRight
	case 0x10F76:
		return joiningClassDual
	case 0x10F77:
		return joiningClassDual
	case 0x10F78:
		return joiningClassDual
	case 0x10F79:
		return joiningClassDual
	case 0x10F7A:
		return joiningClassDual
	case 0x10F7B:
		return joiningClassDual
	case 0x10F7C:
		return joiningClassDual
	case 0x10F7D:
		return joiningClassDual
	case 0x10F7E:
		return joiningClassDual
	case 0x10F7F:
		return joiningClassDual
	case 0x10F80:
		return joiningClassDual
	case 0x10F81:
		return joiningClassDual
	case 0x10FB0:
		return joiningClassDual
	case 0x10FB1:
		return joiningClassNon
	case 0x10FB2:
		return joiningClassDual
	case 0x10FB3:
		return joiningClassDual
	case 0x10FB4:
		return joiningClassRight
	case 0x10FB5:
		return joiningClassRight
	case 0x10FB6:
		return joiningClassRight
	case 0x10FB7:
		return joiningClassNon
	case 0x10FB8:
		return joiningClassDual
	case 0x10FB9:
		return joiningClassRight
	case 0x10FBA:
		return joiningClassRight
	case 0x10FBB:
		return joiningClassDual
	case 0x10FBC:
		return joiningClassDual
	case 0x10FBD:
		return joiningClassRight
	case 0x10FBE:
		return joiningClassDual
	case 0x10FBF:
		return joiningClassDual
	case 0x10FC0:
		return joiningClassNon
	case 0x10FC1:
		return joiningClassDual
	case 0x10FC2:
		return joiningClassRight
	case 0x10FC3:
		return joiningClassRight
	case 0x10FC4:
		return joiningClassDual
	case 0x10FC5:
		return joiningClassNon
	case 0x10FC6:
		return joiningClassNon
	case 0x10FC7:
		return joiningClassNon
	case 0x10FC8:
		return joiningClassNon
	case 0x10FC9:
		return joiningClassRight
	case 0x10FCA:
		return joiningClassDual
	case 0x10FCB:
		return joiningClassLeft
	case 0x110BD:
		return joiningClassNon
	case 0x110CD:
		return joiningClassNon
	case 0x1E900:
		return joiningClassDual
	case 0x1E901:
		return joiningClassDual
	case 0x1E902:
		return joiningClassDual
	case 0x1E903:
		return joiningClassDual
	case 0x1E904:
		return joiningClassDual
	case 0x1E905:
		return joiningClassDual
	case 0x1E906:
		return joiningClassDual
	case 0x1E907:
		return joiningClassDual
	case 0x1E908:
		return joiningClassDual
	case 0x1E909:
		return joiningClassDual
	case 0x1E90A:
		return joiningClassDual
	case 0x1E90B:
		return joiningClassDual
	case 0x1E90C:
		return joiningClassDual
	case 0x1E90D:
		return joiningClassDual
	case 0x1E90E:
		return joiningClassDual
	case 0x1E90F:
		return joiningClassDual
	case 0x1E910:
		return joiningClassDual
	case 0x1E911:
		return joiningClassDual
	case 0x1E912:
		return joiningClassDual
	case 0x1E913:
		return joiningClassDual
	case 0x1E914:
		return joiningClassDual
	case 0x1E915:
		return joiningClassDual
	case 0x1E916:
		return joiningClassDual
	case 0x1E917:
		return joiningClassDual
	case 0x1E918:
		return joiningClassDual
	case 0x1E919:
		return joiningClassDual
	case 0x1E91A:
		return joiningClassDual
	case 0x1E91B:
		return joiningClassDual
	case 0x1E91C:
		return joiningClassDual
	case 0x1E91D:
		return joiningClassDual
	case 0x1E91E:
		return joiningClassDual
	case 0x1E91F:
		return joiningClassDual
	case 0x1E920:
		return joiningClassDual
	case 0x1E921:
		return joiningClassDual
	case 0x1E922:
		return joiningClassDual
	case 0x1E923:
		return joiningClassDual
	case 0x1E924:
		return joiningClassDual
	case 0x1E925:
		return joiningClassDual
	case 0x1E926:
		return joiningClassDual
	case 0x1E927:
		return joiningClassDual
	case 0x1E928:
		return joiningClassDual
	case 0x1E929:
		return joiningClassDual
	case 0x1E92A:
		return joiningClassDual
	case 0x1E92B:
		return joiningClassDual
	case 0x1E92C:
		return joiningClassDual
	case 0x1E92D:
		return joiningClassDual
	case 0x1E92E:
		return joiningClassDual
	case 0x1E92F:
		return joiningClassDual
	case 0x1E930:
		return joiningClassDual
	case 0x1E931:
		return joiningClassDual
	case 0x1E932:
		return joiningClassDual
	case 0x1E933:
		return joiningClassDual
	case 0x1E934:
		return joiningClassDual
	case 0x1E935:
		return joiningClassDual
	case 0x1E936:
		return joiningClassDual
	case 0x1E937:
		return joiningClassDual
	case 0x1E938:
		return joiningClassDual
	case 0x1E939:
		return joiningClassDual
	case 0x1E93A:
		return joiningClassDual
	case 0x1E93B:
		return joiningClassDual
	case 0x1E93C:
		return joiningClassDual
	case 0x1E93D:
		return joiningClassDual
	case 0x1E93E:
		return joiningClassDual
	case 0x1E93F:
		return joiningClassDual
	case 0x1E940:
		return joiningClassDual
	case 0x1E941:
		return joiningClassDual
	case 0x1E942:
		return joiningClassDual
	case 0x1E943:
		return joiningClassDual
	case 0x1E94B:
		return joiningClassTrans
	}
	return joiningClassNon
}

// joiningGroup returns the Joining_Group property for r.
// Returns "No_Joining_Group" if r has no explicit joining group.
// Source: ArabicShaping-17.0.0.txt
func joiningGroup(r rune) string {
	switch r {
	case 0x0620:
		return "KASHMIRI YEH"
	case 0x0622:
		return "ALEF"
	case 0x0623:
		return "ALEF"
	case 0x0624:
		return "WAW"
	case 0x0625:
		return "ALEF"
	case 0x0626:
		return "YEH"
	case 0x0627:
		return "ALEF"
	case 0x0628:
		return "BEH"
	case 0x0629:
		return "TEH MARBUTA"
	case 0x062A:
		return "BEH"
	case 0x062B:
		return "BEH"
	case 0x062C:
		return "HAH"
	case 0x062D:
		return "HAH"
	case 0x062E:
		return "HAH"
	case 0x062F:
		return "DAL"
	case 0x0630:
		return "DAL"
	case 0x0631:
		return "REH"
	case 0x0632:
		return "REH"
	case 0x0633:
		return "SEEN"
	case 0x0634:
		return "SEEN"
	case 0x0635:
		return "SAD"
	case 0x0636:
		return "SAD"
	case 0x0637:
		return "TAH"
	case 0x0638:
		return "TAH"
	case 0x0639:
		return "AIN"
	case 0x063A:
		return "AIN"
	case 0x063B:
		return "GAF"
	case 0x063C:
		return "GAF"
	case 0x063D:
		return "FARSI YEH"
	case 0x063E:
		return "FARSI YEH"
	case 0x063F:
		return "FARSI YEH"
	case 0x0641:
		return "FEH"
	case 0x0642:
		return "QAF"
	case 0x0643:
		return "KAF"
	case 0x0644:
		return "LAM"
	case 0x0645:
		return "MEEM"
	case 0x0646:
		return "NOON"
	case 0x0647:
		return "HEH"
	case 0x0648:
		return "WAW"
	case 0x0649:
		return "YEH"
	case 0x064A:
		return "YEH"
	case 0x066E:
		return "BEH"
	case 0x066F:
		return "QAF"
	case 0x0671:
		return "ALEF"
	case 0x0672:
		return "ALEF"
	case 0x0673:
		return "ALEF"
	case 0x0675:
		return "ALEF"
	case 0x0676:
		return "WAW"
	case 0x0677:
		return "WAW"
	case 0x0678:
		return "YEH"
	case 0x0679:
		return "BEH"
	case 0x067A:
		return "BEH"
	case 0x067B:
		return "BEH"
	case 0x067C:
		return "BEH"
	case 0x067D:
		return "BEH"
	case 0x067E:
		return "BEH"
	case 0x067F:
		return "BEH"
	case 0x0680:
		return "BEH"
	case 0x0681:
		return "HAH"
	case 0x0682:
		return "HAH"
	case 0x0683:
		return "HAH"
	case 0x0684:
		return "HAH"
	case 0x0685:
		return "HAH"
	case 0x0686:
		return "HAH"
	case 0x0687:
		return "HAH"
	case 0x0688:
		return "DAL"
	case 0x0689:
		return "DAL"
	case 0x068A:
		return "DAL"
	case 0x068B:
		return "DAL"
	case 0x068C:
		return "DAL"
	case 0x068D:
		return "DAL"
	case 0x068E:
		return "DAL"
	case 0x068F:
		return "DAL"
	case 0x0690:
		return "DAL"
	case 0x0691:
		return "REH"
	case 0x0692:
		return "REH"
	case 0x0693:
		return "REH"
	case 0x0694:
		return "REH"
	case 0x0695:
		return "REH"
	case 0x0696:
		return "REH"
	case 0x0697:
		return "REH"
	case 0x0698:
		return "REH"
	case 0x0699:
		return "REH"
	case 0x069A:
		return "SEEN"
	case 0x069B:
		return "SEEN"
	case 0x069C:
		return "SEEN"
	case 0x069D:
		return "SAD"
	case 0x069E:
		return "SAD"
	case 0x069F:
		return "TAH"
	case 0x06A0:
		return "AIN"
	case 0x06A1:
		return "FEH"
	case 0x06A2:
		return "FEH"
	case 0x06A3:
		return "FEH"
	case 0x06A4:
		return "FEH"
	case 0x06A5:
		return "FEH"
	case 0x06A6:
		return "FEH"
	case 0x06A7:
		return "QAF"
	case 0x06A8:
		return "QAF"
	case 0x06A9:
		return "GAF"
	case 0x06AA:
		return "SWASH KAF"
	case 0x06AB:
		return "GAF"
	case 0x06AC:
		return "KAF"
	case 0x06AD:
		return "KAF"
	case 0x06AE:
		return "KAF"
	case 0x06AF:
		return "GAF"
	case 0x06B0:
		return "GAF"
	case 0x06B1:
		return "GAF"
	case 0x06B2:
		return "GAF"
	case 0x06B3:
		return "GAF"
	case 0x06B4:
		return "GAF"
	case 0x06B5:
		return "LAM"
	case 0x06B6:
		return "LAM"
	case 0x06B7:
		return "LAM"
	case 0x06B8:
		return "LAM"
	case 0x06B9:
		return "NOON"
	case 0x06BA:
		return "NOON"
	case 0x06BB:
		return "NOON"
	case 0x06BC:
		return "NOON"
	case 0x06BD:
		return "NYA"
	case 0x06BE:
		return "KNOTTED HEH"
	case 0x06BF:
		return "HAH"
	case 0x06C0:
		return "TEH MARBUTA"
	case 0x06C1:
		return "HEH GOAL"
	case 0x06C2:
		return "HEH GOAL"
	case 0x06C3:
		return "TEH MARBUTA GOAL"
	case 0x06C4:
		return "WAW"
	case 0x06C5:
		return "WAW"
	case 0x06C6:
		return "WAW"
	case 0x06C7:
		return "WAW"
	case 0x06C8:
		return "WAW"
	case 0x06C9:
		return "WAW"
	case 0x06CA:
		return "WAW"
	case 0x06CB:
		return "WAW"
	case 0x06CC:
		return "FARSI YEH"
	case 0x06CD:
		return "YEH WITH TAIL"
	case 0x06CE:
		return "FARSI YEH"
	case 0x06CF:
		return "WAW"
	case 0x06D0:
		return "YEH"
	case 0x06D1:
		return "YEH"
	case 0x06D2:
		return "YEH BARREE"
	case 0x06D3:
		return "YEH BARREE"
	case 0x06D5:
		return "TEH MARBUTA"
	case 0x06EE:
		return "DAL"
	case 0x06EF:
		return "REH"
	case 0x06FA:
		return "SEEN"
	case 0x06FB:
		return "SAD"
	case 0x06FC:
		return "AIN"
	case 0x06FF:
		return "KNOTTED HEH"
	case 0x0710:
		return "ALAPH"
	case 0x0712:
		return "BETH"
	case 0x0713:
		return "GAMAL"
	case 0x0714:
		return "GAMAL"
	case 0x0715:
		return "DALATH RISH"
	case 0x0716:
		return "DALATH RISH"
	case 0x0717:
		return "HE"
	case 0x0718:
		return "SYRIAC WAW"
	case 0x0719:
		return "ZAIN"
	case 0x071A:
		return "HETH"
	case 0x071B:
		return "TETH"
	case 0x071C:
		return "TETH"
	case 0x071D:
		return "YUDH"
	case 0x071E:
		return "YUDH HE"
	case 0x071F:
		return "KAPH"
	case 0x0720:
		return "LAMADH"
	case 0x0721:
		return "MIM"
	case 0x0722:
		return "NUN"
	case 0x0723:
		return "SEMKATH"
	case 0x0724:
		return "FINAL SEMKATH"
	case 0x0725:
		return "E"
	case 0x0726:
		return "PE"
	case 0x0727:
		return "REVERSED PE"
	case 0x0728:
		return "SADHE"
	case 0x0729:
		return "QAPH"
	case 0x072A:
		return "DALATH RISH"
	case 0x072B:
		return "SHIN"
	case 0x072C:
		return "TAW"
	case 0x072D:
		return "BETH"
	case 0x072E:
		return "GAMAL"
	case 0x072F:
		return "DALATH RISH"
	case 0x074D:
		return "ZHAIN"
	case 0x074E:
		return "KHAPH"
	case 0x074F:
		return "FE"
	case 0x0750:
		return "BEH"
	case 0x0751:
		return "BEH"
	case 0x0752:
		return "BEH"
	case 0x0753:
		return "BEH"
	case 0x0754:
		return "BEH"
	case 0x0755:
		return "BEH"
	case 0x0756:
		return "BEH"
	case 0x0757:
		return "HAH"
	case 0x0758:
		return "HAH"
	case 0x0759:
		return "DAL"
	case 0x075A:
		return "DAL"
	case 0x075B:
		return "REH"
	case 0x075C:
		return "SEEN"
	case 0x075D:
		return "AIN"
	case 0x075E:
		return "AIN"
	case 0x075F:
		return "AIN"
	case 0x0760:
		return "FEH"
	case 0x0761:
		return "FEH"
	case 0x0762:
		return "GAF"
	case 0x0763:
		return "GAF"
	case 0x0764:
		return "GAF"
	case 0x0765:
		return "MEEM"
	case 0x0766:
		return "MEEM"
	case 0x0767:
		return "NOON"
	case 0x0768:
		return "NOON"
	case 0x0769:
		return "NOON"
	case 0x076A:
		return "LAM"
	case 0x076B:
		return "REH"
	case 0x076C:
		return "REH"
	case 0x076D:
		return "SEEN"
	case 0x076E:
		return "HAH"
	case 0x076F:
		return "HAH"
	case 0x0770:
		return "SEEN"
	case 0x0771:
		return "REH"
	case 0x0772:
		return "HAH"
	case 0x0773:
		return "ALEF"
	case 0x0774:
		return "ALEF"
	case 0x0775:
		return "FARSI YEH"
	case 0x0776:
		return "FARSI YEH"
	case 0x0777:
		return "YEH"
	case 0x0778:
		return "WAW"
	case 0x0779:
		return "WAW"
	case 0x077A:
		return "BURUSHASKI YEH BARREE"
	case 0x077B:
		return "BURUSHASKI YEH BARREE"
	case 0x077C:
		return "HAH"
	case 0x077D:
		return "SEEN"
	case 0x077E:
		return "SEEN"
	case 0x077F:
		return "KAF"
	case 0x0860:
		return "MALAYALAM NGA"
	case 0x0861:
		return "MALAYALAM JA"
	case 0x0862:
		return "MALAYALAM NYA"
	case 0x0863:
		return "MALAYALAM TTA"
	case 0x0864:
		return "MALAYALAM NNA"
	case 0x0865:
		return "MALAYALAM NNNA"
	case 0x0866:
		return "MALAYALAM BHA"
	case 0x0867:
		return "MALAYALAM RA"
	case 0x0868:
		return "MALAYALAM LLA"
	case 0x0869:
		return "MALAYALAM LLLA"
	case 0x086A:
		return "MALAYALAM SSA"
	case 0x0870:
		return "ALEF"
	case 0x0871:
		return "ALEF"
	case 0x0872:
		return "ALEF"
	case 0x0873:
		return "ALEF"
	case 0x0874:
		return "ALEF"
	case 0x0875:
		return "ALEF"
	case 0x0876:
		return "ALEF"
	case 0x0877:
		return "ALEF"
	case 0x0878:
		return "ALEF"
	case 0x0879:
		return "ALEF"
	case 0x087A:
		return "ALEF"
	case 0x087B:
		return "ALEF"
	case 0x087C:
		return "ALEF"
	case 0x087D:
		return "ALEF"
	case 0x087E:
		return "ALEF"
	case 0x087F:
		return "ALEF"
	case 0x0880:
		return "ALEF"
	case 0x0881:
		return "ALEF"
	case 0x0882:
		return "ALEF"
	case 0x0886:
		return "THIN YEH"
	case 0x0889:
		return "NOON"
	case 0x088A:
		return "HAH"
	case 0x088B:
		return "TAH"
	case 0x088C:
		return "TAH"
	case 0x088D:
		return "GAF"
	case 0x088E:
		return "VERTICAL TAIL"
	case 0x088F:
		return "NOON"
	case 0x08A0:
		return "BEH"
	case 0x08A1:
		return "BEH"
	case 0x08A2:
		return "HAH"
	case 0x08A3:
		return "TAH"
	case 0x08A4:
		return "FEH"
	case 0x08A5:
		return "QAF"
	case 0x08A6:
		return "LAM"
	case 0x08A7:
		return "MEEM"
	case 0x08A8:
		return "YEH"
	case 0x08A9:
		return "YEH"
	case 0x08AA:
		return "REH"
	case 0x08AB:
		return "WAW"
	case 0x08AC:
		return "ROHINGYA YEH"
	case 0x08AE:
		return "DAL"
	case 0x08AF:
		return "SAD"
	case 0x08B0:
		return "GAF"
	case 0x08B1:
		return "STRAIGHT WAW"
	case 0x08B2:
		return "REH"
	case 0x08B3:
		return "AIN"
	case 0x08B4:
		return "KAF"
	case 0x08B5:
		return "QAF"
	case 0x08B6:
		return "BEH"
	case 0x08B7:
		return "BEH"
	case 0x08B8:
		return "BEH"
	case 0x08B9:
		return "REH"
	case 0x08BA:
		return "YEH"
	case 0x08BB:
		return "AFRICAN FEH"
	case 0x08BC:
		return "AFRICAN QAF"
	case 0x08BD:
		return "AFRICAN NOON"
	case 0x08BE:
		return "BEH"
	case 0x08BF:
		return "BEH"
	case 0x08C0:
		return "BEH"
	case 0x08C1:
		return "HAH"
	case 0x08C2:
		return "GAF"
	case 0x08C3:
		return "AIN"
	case 0x08C4:
		return "AFRICAN QAF"
	case 0x08C5:
		return "HAH"
	case 0x08C6:
		return "HAH"
	case 0x08C7:
		return "LAM"
	case 0x08C8:
		return "GAF"
	case 0x10AC0:
		return "MANICHAEAN ALEPH"
	case 0x10AC1:
		return "MANICHAEAN BETH"
	case 0x10AC2:
		return "MANICHAEAN BETH"
	case 0x10AC3:
		return "MANICHAEAN GIMEL"
	case 0x10AC4:
		return "MANICHAEAN GIMEL"
	case 0x10AC5:
		return "MANICHAEAN DALETH"
	case 0x10AC7:
		return "MANICHAEAN WAW"
	case 0x10AC9:
		return "MANICHAEAN ZAYIN"
	case 0x10ACA:
		return "MANICHAEAN ZAYIN"
	case 0x10ACD:
		return "MANICHAEAN HETH"
	case 0x10ACE:
		return "MANICHAEAN TETH"
	case 0x10ACF:
		return "MANICHAEAN YODH"
	case 0x10AD0:
		return "MANICHAEAN KAPH"
	case 0x10AD1:
		return "MANICHAEAN KAPH"
	case 0x10AD2:
		return "MANICHAEAN KAPH"
	case 0x10AD3:
		return "MANICHAEAN LAMEDH"
	case 0x10AD4:
		return "MANICHAEAN DHAMEDH"
	case 0x10AD5:
		return "MANICHAEAN THAMEDH"
	case 0x10AD6:
		return "MANICHAEAN MEM"
	case 0x10AD7:
		return "MANICHAEAN NUN"
	case 0x10AD8:
		return "MANICHAEAN SAMEKH"
	case 0x10AD9:
		return "MANICHAEAN AYIN"
	case 0x10ADA:
		return "MANICHAEAN AYIN"
	case 0x10ADB:
		return "MANICHAEAN PE"
	case 0x10ADC:
		return "MANICHAEAN PE"
	case 0x10ADD:
		return "MANICHAEAN SADHE"
	case 0x10ADE:
		return "MANICHAEAN QOPH"
	case 0x10ADF:
		return "MANICHAEAN QOPH"
	case 0x10AE0:
		return "MANICHAEAN QOPH"
	case 0x10AE1:
		return "MANICHAEAN RESH"
	case 0x10AE4:
		return "MANICHAEAN TAW"
	case 0x10AEB:
		return "MANICHAEAN ONE"
	case 0x10AEC:
		return "MANICHAEAN FIVE"
	case 0x10AED:
		return "MANICHAEAN TEN"
	case 0x10AEE:
		return "MANICHAEAN TWENTY"
	case 0x10AEF:
		return "MANICHAEAN HUNDRED"
	case 0x10D02:
		return "HANIFI ROHINGYA PA"
	case 0x10D09:
		return "HANIFI ROHINGYA PA"
	case 0x10D19:
		return "HANIFI ROHINGYA KINNA YA"
	case 0x10D1C:
		return "HANIFI ROHINGYA PA"
	case 0x10D1E:
		return "HANIFI ROHINGYA KINNA YA"
	case 0x10D20:
		return "HANIFI ROHINGYA KINNA YA"
	case 0x10D23:
		return "HANIFI ROHINGYA KINNA YA"
	case 0x10EC2:
		return "DAL"
	case 0x10EC3:
		return "TAH"
	case 0x10EC4:
		return "KAF"
	case 0x10EC6:
		return "THIN NOON"
	case 0x10EC7:
		return "YEH"
	}
	return "No_Joining_Group"
}

// arabicForm holds the four Presentation Forms-B code points for one
// Arabic base letter. Zero means the form is absent in the Pres-B block.
// Source: UnicodeData-17.0.0.txt decomposition mappings.
type arabicForm struct {
	isolated, final, initial, medial rune
}

// HasIsolated reports whether an isolated presentation form exists.
func (f arabicForm) HasIsolated() bool { return f.isolated != 0 }

// HasFinal reports whether a final presentation form exists.
func (f arabicForm) HasFinal() bool { return f.final != 0 }

// HasInitial reports whether an initial presentation form exists.
func (f arabicForm) HasInitial() bool { return f.initial != 0 }

// HasMedial reports whether a medial presentation form exists.
func (f arabicForm) HasMedial() bool { return f.medial != 0 }

// arabicForms lists the 36 base letters that have Presentation Forms-B
// entries, sorted by base code point for binary search via arabicFormOf.
var arabicForms = [...]struct {
	base rune
	form arabicForm
}{
	{0x0621, arabicForm{0xFE80, 0x0000, 0x0000, 0x0000}},
	{0x0622, arabicForm{0xFE81, 0xFE82, 0x0000, 0x0000}},
	{0x0623, arabicForm{0xFE83, 0xFE84, 0x0000, 0x0000}},
	{0x0624, arabicForm{0xFE85, 0xFE86, 0x0000, 0x0000}},
	{0x0625, arabicForm{0xFE87, 0xFE88, 0x0000, 0x0000}},
	{0x0626, arabicForm{0xFE89, 0xFE8A, 0xFE8B, 0xFE8C}},
	{0x0627, arabicForm{0xFE8D, 0xFE8E, 0x0000, 0x0000}},
	{0x0628, arabicForm{0xFE8F, 0xFE90, 0xFE91, 0xFE92}},
	{0x0629, arabicForm{0xFE93, 0xFE94, 0x0000, 0x0000}},
	{0x062A, arabicForm{0xFE95, 0xFE96, 0xFE97, 0xFE98}},
	{0x062B, arabicForm{0xFE99, 0xFE9A, 0xFE9B, 0xFE9C}},
	{0x062C, arabicForm{0xFE9D, 0xFE9E, 0xFE9F, 0xFEA0}},
	{0x062D, arabicForm{0xFEA1, 0xFEA2, 0xFEA3, 0xFEA4}},
	{0x062E, arabicForm{0xFEA5, 0xFEA6, 0xFEA7, 0xFEA8}},
	{0x062F, arabicForm{0xFEA9, 0xFEAA, 0x0000, 0x0000}},
	{0x0630, arabicForm{0xFEAB, 0xFEAC, 0x0000, 0x0000}},
	{0x0631, arabicForm{0xFEAD, 0xFEAE, 0x0000, 0x0000}},
	{0x0632, arabicForm{0xFEAF, 0xFEB0, 0x0000, 0x0000}},
	{0x0633, arabicForm{0xFEB1, 0xFEB2, 0xFEB3, 0xFEB4}},
	{0x0634, arabicForm{0xFEB5, 0xFEB6, 0xFEB7, 0xFEB8}},
	{0x0635, arabicForm{0xFEB9, 0xFEBA, 0xFEBB, 0xFEBC}},
	{0x0636, arabicForm{0xFEBD, 0xFEBE, 0xFEBF, 0xFEC0}},
	{0x0637, arabicForm{0xFEC1, 0xFEC2, 0xFEC3, 0xFEC4}},
	{0x0638, arabicForm{0xFEC5, 0xFEC6, 0xFEC7, 0xFEC8}},
	{0x0639, arabicForm{0xFEC9, 0xFECA, 0xFECB, 0xFECC}},
	{0x063A, arabicForm{0xFECD, 0xFECE, 0xFECF, 0xFED0}},
	{0x0641, arabicForm{0xFED1, 0xFED2, 0xFED3, 0xFED4}},
	{0x0642, arabicForm{0xFED5, 0xFED6, 0xFED7, 0xFED8}},
	{0x0643, arabicForm{0xFED9, 0xFEDA, 0xFEDB, 0xFEDC}},
	{0x0644, arabicForm{0xFEDD, 0xFEDE, 0xFEDF, 0xFEE0}},
	{0x0645, arabicForm{0xFEE1, 0xFEE2, 0xFEE3, 0xFEE4}},
	{0x0646, arabicForm{0xFEE5, 0xFEE6, 0xFEE7, 0xFEE8}},
	{0x0647, arabicForm{0xFEE9, 0xFEEA, 0xFEEB, 0xFEEC}},
	{0x0648, arabicForm{0xFEED, 0xFEEE, 0x0000, 0x0000}},
	{0x0649, arabicForm{0xFEEF, 0xFEF0, 0x0000, 0x0000}},
	{0x064A, arabicForm{0xFEF1, 0xFEF2, 0xFEF3, 0xFEF4}},
}

// arabicFormOf returns the Presentation Forms-B entry for r.
// ok is false when r has no Presentation Forms-B entries.
func arabicFormOf(r rune) (arabicForm, bool) {
	lo, hi := 0, len(arabicForms)-1
	for lo <= hi {
		mid := (lo + hi) >> 1
		switch {
		case arabicForms[mid].base == r:
			return arabicForms[mid].form, true
		case arabicForms[mid].base < r:
			lo = mid + 1
		default:
			hi = mid - 1
		}
	}
	return arabicForm{}, false
}

// shapedRune returns the Presentation Forms-B glyph for r according to its
// joining state (rightJoined and leftJoined).
//
// Logical Preservation Contract:
// If the required presentation form glyph is absent (0x0000) or r has no
// presentation forms at all, shapedRune returns r unchanged.
// For example, U+0649 (Alef Maksura, JT=D) has isolated (0xFEEF) and final (0xFEF0)
// forms, but no initial or medial glyphs in Presentation Forms-B; when in initial
// or medial position, it returns 0x0649 unchanged.
func shapedRune(r rune, rightJoined, leftJoined bool) rune {
	form, ok := arabicFormOf(r)
	if !ok {
		return r
	}
	var shaped rune
	switch {
	case rightJoined && leftJoined:
		shaped = form.medial
	case rightJoined && !leftJoined:
		shaped = form.final
	case !rightJoined && leftJoined:
		shaped = form.initial
	default:
		shaped = form.isolated
	}
	if shaped == 0 {
		return r
	}
	return shaped
}

// lamAlefEntry maps one Alef variant to its Lam-Alef ligature forms.
// The Lam base (U+0644) is implicit.
type lamAlefEntry struct {
	alef               rune // Alef variant
	isolated, finalLig rune // ligature glyphs
}

// lamAlefForms lists the 4 Lam-Alef ligatures, sorted by Alef variant.
// Source: UnicodeData-17.0.0.txt (2-codepoint decompositions 0644+<alef>).
var lamAlefForms = [...]lamAlefEntry{
	{0x0622, 0xFEF5, 0xFEF6}, // Lam + U+0622
	{0x0623, 0xFEF7, 0xFEF8}, // Lam + U+0623
	{0x0625, 0xFEF9, 0xFEFA}, // Lam + U+0625
	{0x0627, 0xFEFB, 0xFEFC}, // Lam + U+0627
}

// lamAlefFormOf returns the ligature forms for a Lam followed by alef.
// ok is false if alef is not one of the recognised Alef variants.
func lamAlefFormOf(alef rune) (isolated, final rune, ok bool) {
	for i := range lamAlefForms {
		if lamAlefForms[i].alef == alef {
			return lamAlefForms[i].isolated, lamAlefForms[i].finalLig, true
		}
	}
	return 0, 0, false
}

// missingFormEntry records a letter whose Joining_Type is D but that has
// no independent initial/medial Presentation Forms-B glyphs.
// Under the Logical Preservation Contract, when shaped into initial or medial
// position, these letters remain their original logical rune.
type missingFormEntry struct {
	base rune
	note string
}

// missingForms lists 73 letter(s) that are JT=D but lack initial/medial
// Presentation Forms-B glyphs. Exposed within internal/rtl for tests and documentation.
var missingForms = [...]missingFormEntry{
	{0x0620, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x063B, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x063C, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x063D, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x063E, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x063F, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x0649, "JT=D but Presentation Forms-B block has no initial/medial glyphs"},
	{0x066E, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x066F, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x0678, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x0679, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x067A, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x067B, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x067C, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x067D, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x067E, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x067F, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x0680, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x0681, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x0682, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x0683, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x0684, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x0685, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x0686, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x0687, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x069A, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x069B, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x069C, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x069D, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x069E, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x069F, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06A0, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06A1, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06A2, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06A3, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06A4, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06A5, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06A6, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06A7, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06A8, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06A9, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06AA, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06AB, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06AC, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06AD, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06AE, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06AF, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06B0, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06B1, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06B2, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06B3, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06B4, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06B5, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06B6, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06B7, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06B8, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06B9, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06BA, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06BB, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06BC, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06BD, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06BE, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06BF, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06C1, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06C2, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06CC, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06CE, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06D0, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06D1, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06FA, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06FB, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06FC, "JT=D but absent from Presentation Forms-B block entirely"},
	{0x06FF, "JT=D but absent from Presentation Forms-B block entirely"},
}

// isMissingForm reports whether r is a dual-joining letter that lacks
// initial/medial presentation forms.
func isMissingForm(r rune) bool {
	lo, hi := 0, len(missingForms)-1
	for lo <= hi {
		mid := (lo + hi) >> 1
		switch {
		case missingForms[mid].base == r:
			return true
		case missingForms[mid].base < r:
			lo = mid + 1
		default:
			hi = mid - 1
		}
	}
	return false
}
